# Uncomment the following line to use OpenMP 2.0 features
#OMPFLAG = -DOMPVER2
# Uncomment the following line to use OpenMP 3.0 features
OMPFLAG = -DDISABLE_BARRIER_TEST -DOMPVER2 -DOMPVER3

CC = gcc
CFLAGS = -fopenmp -O1 -lm
LDFLAGS = -fopenmp -O1 -lm
CPP = /test1/opt/gcc/5.5.0/bin
LIBS = 